# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: sudo apt-get install tree
    - run: tree
    - run: npm install
    - run: npm install -g @angular/cli@latest
    - run : npm install -g ng-openapi-gen
    - run: dir
    - run: ng-openapi-gen --input openapi/swagger.json -o projects/automat-api/src/API | ng build AutomatApie
    - run: ng build AutomatShared
    - run: ng build UserFrontend
    - run: ng build AdminFrontend
